config/routes.rb
Ebook::Application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  resources :agents

  resources :lands

  

end

app/models/land.rb
class Land < ActiveRecord::Base
end

app/models/real_estate.rb
class RealEstate < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
	@title = "All Agents"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lands_controller.rb
class LandsController < ApplicationController
  before_action :set_land, only: [:show, :edit, :update, :destroy]

  # GET /lands
  # GET /lands.json
  def index
    @lands = Land.all
  end

  # GET /lands/1
  # GET /lands/1.json
  def show
  end

  # GET /lands/new
  def new
    @land = Land.new
  end

  # GET /lands/1/edit
  def edit
  end

  # POST /lands
  # POST /lands.json
  def create
    @land = Land.new(land_params)

    respond_to do |format|
      if @land.save
        format.html { redirect_to @land, notice: 'Land was successfully created.' }
        format.json { render action: 'show', status: :created, location: @land }
      else
        format.html { render action: 'new' }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lands/1
  # PATCH/PUT /lands/1.json
  def update
    respond_to do |format|
      if @land.update(land_params)
        format.html { redirect_to @land, notice: 'Land was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @land.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lands/1
  # DELETE /lands/1.json
  def destroy
    @land.destroy
    respond_to do |format|
      format.html { redirect_to lands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_land
      @land = Land.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def land_params
      params.require(:land).permit(:name, :location, :seller, :size, :price, :image)
    end
end

app/controllers/r_estatepages_controller.rb
class REstatepagesController < ApplicationController
end

app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  before_action :set_real_estate, only: [:show, :edit, :update, :destroy]

  # GET /real_estates
  # GET /real_estates.json
  def index
    @real_estates = RealEstate.all
  end

  # GET /real_estates/1
  # GET /real_estates/1.json
  def show
  end

  # GET /real_estates/new
  def new
    @real_estate = RealEstate.new
  end

  # GET /real_estates/1/edit
  def edit
  end

  # POST /real_estates
  # POST /real_estates.json
  def create
    @real_estate = RealEstate.new(real_estate_params)

    respond_to do |format|
      if @real_estate.save
        format.html { redirect_to @real_estate, notice: 'Real estate was successfully created.' }
        format.json { render action: 'show', status: :created, location: @real_estate }
      else
        format.html { render action: 'new' }
        format.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /real_estates/1
  # PATCH/PUT /real_estates/1.json
  def update
    respond_to do |format|
      if @real_estate.update(real_estate_params)
        format.html { redirect_to @real_estate, notice: 'Real estate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /real_estates/1
  # DELETE /real_estates/1.json
  def destroy
    @real_estate.destroy
    respond_to do |format|
      format.html { redirect_to real_estates_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_real_estate
      @real_estate = RealEstate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def real_estate_params
      params.require(:real_estate).permit(:name, :location, :seller, :size, :price, :image_path)
    end
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lands_helper.rb
module LandsHelper
end

app/helpers/r_estatepages_helper.rb
module REstatepagesHelper
end

app/helpers/real_estates_helper.rb
module RealEstatesHelper
end

app/views/agents/index.html.erb
<h1>All users</h1>

app/views/lands/_form.html.erb
<%= form_for(@land) do |f| %>
  <% if @land.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@land.errors.count, "error") %> prohibited this land from being saved:</h2>

      <ul>
      <% @land.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :seller %><br>
    <%= f.text_field :seller %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lands/edit.html.erb
<h1>Editing land</h1>

<%= render 'form' %>

<%= link_to 'Show', @land %> |
<%= link_to 'Back', lands_path %>

app/views/lands/index.html.erb
<h1>Listing lands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Location</th>
      <th>Seller</th>
      <th>Size</th>
      <th>Price</th>
      <th>Image</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lands.each do |land| %>
      <tr>
        <td><%= land.name %></td>
        <td><%= land.location %></td>
        <td><%= land.seller %></td>
        <td><%= land.size %></td>
        <td><%= land.price %></td>
        <td><%= land.image %></td>
        <td><%= link_to 'Show', land %></td>
        <td><%= link_to 'Edit', edit_land_path(land) %></td>
        <td><%= link_to 'Destroy', land, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Land', new_land_path %>

app/views/lands/new.html.erb
<h1>New land</h1>

<%= render 'form' %>

<%= link_to 'Back', lands_path %>

app/views/lands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @land.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @land.location %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @land.seller %>
</p>

<p>
  <strong>Size:</strong>
  <%= @land.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @land.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @land.image %>
</p>

<%= link_to 'Edit', edit_land_path(@land) %> |
<%= link_to 'Back', lands_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RealEstate Connect</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	

<%= yield %>

</body>
</html>

app/views/real_estates/_form.html.erb
<%= form_for(@real_estate) do |f| %>
  <% if @real_estate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@real_estate.errors.count, "error") %> prohibited this real_estate from being saved:</h2>

      <ul>
      <% @real_estate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :seller %><br>
    <%= f.text_field :seller %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :image_path %><br>
    <%= f.text_field :image_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/real_estates/edit.html.erb
<h1>Editing real_estate</h1>

<%= render 'form' %>

<%= link_to 'Show', @real_estate %> |
<%= link_to 'Back', real_estates_path %>

app/views/real_estates/index.html.erb
<div class="container">
<h3 class="text-info">RealEstate Connect</h3>
  <% @real_estates.each do |real_estate| %>
    
  <div class="row">
    <p class="<%= cycle('list_line_odd' , 'list_line_even' ) %>"></p>
    <div class="span3 pull-left">
        <%= image_tag(real_estate.image_path, :class => 'list_image' ) %>
        <p><%= real_estate.name %></p>
        <p><%= real_estate.location %></p>
        <p><%= real_estate.seller %></p>
        <p><%= real_estate.size %></p>
        <p><%= real_estate.price %></p>
        <p><%= link_to 'Show', real_estate %>
        <%= link_to 'Edit', edit_real_estate_path(real_estate) %>
        <%= link_to 'Destroy', real_estate, method: :delete, data: { confirm: 'Are you sure?' } %><P>



    </div>
    <div class="span6">
       
          <% end %>
  
      <br>
      <br>
      <p class="pull-right">
      <%= link_to 'New Real estate', new_real_estate_path %>
      </p>
    </div>
   
  </div>
</div> 
  
    

app/views/real_estates/new.html.erb
<h1>New real_estate</h1>
<div class="offset6">
<%= render 'form' %>

<%= link_to 'Back', real_estates_path %>
</div> 

app/views/real_estates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @real_estate.name %>
</p>

<p>
  <strong>Location:</strong>
  <%= @real_estate.location %>
</p>

<p>
  <strong>Seller:</strong>
  <%= @real_estate.seller %>
</p>

<p>
  <strong>Size:</strong>
  <%= @real_estate.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @real_estate.price %>
</p>

<p>
  <strong>Image path:</strong>
  <%= @real_estate.image_path %>
</p>

<%= link_to 'Edit', edit_real_estate_path(@real_estate) %> |
<%= link_to 'Back', real_estates_path %>